options:
  couch-user:
    type: string
    default: "couchuser"
    description: "The user account to install couchpotato as"
  port:
    type: int
    default: 5050
    description: "Port that couchpotato listens to"
  restore-config:
    type: boolean
    default: False
    description: "Restore configuration from backup resource"
  proxy-port:
    type: int
    default: 443
    description: "Port to request for reverse proxy access"
  proxy-domain:
    type: string
    default: "couchpotato"
    description: "Subdomain to request from reverse proxy"
  proxy-url:
    type: string
    default: "/couchpotato"
    description: 'Urlbase for revrse proxy, must start with a "/"'
  backup-count:
    type: int
    default: 0
    description: "Number of backups to keep"
  backup-cron:
    type: string
    default: "@daily"
    description: "Interval to create backup, takes a cron compatible string"
  backup-location:
    type: string
    default: ""
    description: "Location to store backups"

